field_types:
  review_id: 'token'
  user_id: 'token'
  item_id: 'token'
  useful: 'float'
  funny: 'float'
  cool: 'float'
  timestamp: 'float'
  rating: 'float'

dataset:
  field_separator: "\t"
  USER_ID_FIELD: 'user_id:token'
  ITEM_ID_FIELD: 'item_id:token'
  TIME_FIELD: 'timestamp:float'
  LABEL_FIELD: 'rating:float'


metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'GiniIndex', 'TailPercentage']
learning_rate: 0.001
batch_size: 256
epochs: 20
eval_args:
  split:
    RS: [0.65, 0.15, 0.2]
  order: 'TO'
  group_by: 'user_id:token'
